// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260824061338_AddCarpooling")]
    partial class AddCarpooling
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualDropTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ActualPickupTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ActualPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CouponId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<decimal?>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DistanceInKm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("DriverId")
                        .HasColumnType("int");

                    b.Property<string>("DropLocation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("EstimatedPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PickupDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PickupLocation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SpecialInstructions")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CouponId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PickupDate");

                    b.HasIndex("Status");

                    b.HasIndex("VehicleId");

                    b.HasIndex("CustomerId", "Status");

                    b.HasIndex("DriverId", "Status");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("backend.Models.CarpoolBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int?>("PaymentId")
                        .HasColumnType("int");

                    b.Property<int>("RideOfferId")
                        .HasColumnType("int");

                    b.Property<int>("SeatsBooked")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId");

                    b.HasIndex("Status");

                    b.HasIndex("CustomerId", "Status");

                    b.HasIndex("RideOfferId", "CustomerId");

                    b.ToTable("CarpoolBookings");
                });

            modelBuilder.Entity("backend.Models.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentUsageCount")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("DiscountPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MaxDiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaxUsageCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("MinOrderAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ValidFrom");

                    b.HasIndex("ValidUntil");

                    b.HasIndex("IsActive", "ValidFrom", "ValidUntil");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "WELCOME10",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentUsageCount = 0,
                            Description = "Welcome offer - 10% off",
                            DiscountPercentage = 10m,
                            IsActive = true,
                            MaxDiscountAmount = 100m,
                            MaxUsageCount = 1000,
                            MinOrderAmount = 200m,
                            ValidFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValidUntil = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Code = "FIRSTRIDE",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentUsageCount = 0,
                            Description = "First ride free up to ₹150",
                            DiscountPercentage = 100m,
                            IsActive = true,
                            MaxDiscountAmount = 150m,
                            MaxUsageCount = 500,
                            MinOrderAmount = 100m,
                            ValidFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValidUntil = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Code = "WEEKEND20",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentUsageCount = 0,
                            Description = "Weekend special - 20% off",
                            DiscountPercentage = 20m,
                            IsActive = true,
                            MaxDiscountAmount = 200m,
                            MaxUsageCount = 200,
                            MinOrderAmount = 300m,
                            ValidFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValidUntil = new DateTime(2024, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("backend.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber");

                    b.HasIndex("FirstName", "LastName");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("backend.Models.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastActiveAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("LicenseExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Rating")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TotalTrips")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("LicenseNumber")
                        .IsUnique();

                    b.HasIndex("PhoneNumber");

                    b.HasIndex("Rating");

                    b.HasIndex("Status");

                    b.HasIndex("FirstName", "LastName");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("backend.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Type");

                    b.HasIndex("CustomerId", "IsRead");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("backend.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentGatewayResponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.HasIndex("TransactionId")
                        .IsUnique()
                        .HasFilter("[TransactionId] IS NOT NULL");

                    b.HasIndex("CustomerId", "Status");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("backend.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int?>("DriverId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDriverReview")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVehicleReview")
                        .HasColumnType("bit");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CustomerId");

                    b.HasIndex("Rating");

                    b.HasIndex("DriverId", "IsDriverReview");

                    b.HasIndex("VehicleId", "IsVehicleReview");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("backend.Models.RideOffer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DestinationCity")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("DestinationLat")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal?>("DestinationLng")
                        .HasPrecision(11, 7)
                        .HasColumnType("decimal(11,7)");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<decimal?>("EstimatedDistanceKm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("EstimatedDurationMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("InstantBooking")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxPassengersInBack")
                        .HasColumnType("int");

                    b.Property<string>("OriginAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OriginCity")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("OriginLat")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal?>("OriginLng")
                        .HasPrecision(11, 7)
                        .HasColumnType("decimal(11,7)");

                    b.Property<bool>("PetsAllowed")
                        .HasColumnType("bit");

                    b.Property<decimal>("PricePerSeat")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("SmokingAllowed")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartureTime");

                    b.HasIndex("DriverId");

                    b.HasIndex("Status");

                    b.HasIndex("VehicleId");

                    b.HasIndex("OriginCity", "DestinationCity", "DepartureTime");

                    b.ToTable("RideOffers");
                });

            modelBuilder.Entity("backend.Models.RideRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("BookingId", "DriverId")
                        .IsUnique();

                    b.ToTable("RideRequests");
                });

            modelBuilder.Entity("backend.Models.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActualDurationMinutes")
                        .HasColumnType("int");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DistanceInKm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("EndLatitude")
                        .HasPrecision(10, 8)
                        .HasColumnType("decimal(10,8)");

                    b.Property<string>("EndLocation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("EndLongitude")
                        .HasPrecision(11, 8)
                        .HasColumnType("decimal(11,8)");

                    b.Property<int>("EstimatedDurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("RoutePolyline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("StartLatitude")
                        .HasPrecision(10, 8)
                        .HasColumnType("decimal(10,8)");

                    b.Property<string>("StartLocation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("StartLongitude")
                        .HasPrecision(11, 8)
                        .HasColumnType("decimal(11,8)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("backend.Models.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DriverId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DriverId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("backend.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CurrentDriverId")
                        .HasColumnType("int");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PricePerDay")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PricePerKm")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SeatingCapacity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("VehicleCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurrentDriverId");

                    b.HasIndex("IsAvailable");

                    b.HasIndex("RegistrationNumber")
                        .IsUnique();

                    b.HasIndex("VehicleCategoryId");

                    b.HasIndex("VehicleType");

                    b.HasIndex("Make", "Model");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelType = "Petrol",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/2018_Suzuki_Swift_%28AZ%2C_facelift%29_1.2_GL_sedan_%282019-03-13%29_01.jpg/320px-2018_Suzuki_Swift_%28AZ%2C_facelift%29_1.2_GL_sedan_%282019-03-13%29_01.jpg",
                            IsActive = true,
                            IsAvailable = true,
                            Make = "Maruti Suzuki",
                            Model = "Swift",
                            PricePerDay = 150m,
                            PricePerKm = 8m,
                            RegistrationNumber = "MH12AB1234",
                            SeatingCapacity = 4,
                            VehicleCategoryId = 1,
                            VehicleType = "MiniCab",
                            Year = 2022
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelType = "Petrol",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/2020_Hyundai_i20_%28BC3%29_Elite_sedan_%282021-07-25%29_01.jpg/320px-2020_Hyundai_i20_%28BC3%29_Elite_sedan_%282021-07-25%29_01.jpg",
                            IsActive = true,
                            IsAvailable = true,
                            Make = "Hyundai",
                            Model = "i20",
                            PricePerDay = 160m,
                            PricePerKm = 8m,
                            RegistrationNumber = "DL09CD2345",
                            SeatingCapacity = 5,
                            VehicleCategoryId = 1,
                            VehicleType = "MiniCab",
                            Year = 2023
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelType = "Petrol",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Tata_Tiago_facelift_%28front%29.jpg/320px-Tata_Tiago_facelift_%28front%29.jpg",
                            IsActive = true,
                            IsAvailable = true,
                            Make = "Tata",
                            Model = "Tiago",
                            PricePerDay = 140m,
                            PricePerKm = 7m,
                            RegistrationNumber = "KA05EF3456",
                            SeatingCapacity = 5,
                            VehicleCategoryId = 1,
                            VehicleType = "MiniCab",
                            Year = 2023
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelType = "Petrol",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/2021_Honda_City_RS_e%3AHEV_%28GM6%29_%28front%29.jpg/320px-2021_Honda_City_RS_e%3AHEV_%28GM6%29_%28front%29.jpg",
                            IsActive = true,
                            IsAvailable = true,
                            Make = "Honda",
                            Model = "City",
                            PricePerDay = 300m,
                            PricePerKm = 12m,
                            RegistrationNumber = "KA01CD5678",
                            SeatingCapacity = 5,
                            VehicleCategoryId = 2,
                            VehicleType = "Sedan",
                            Year = 2023
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelType = "Petrol",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/2023_Hyundai_Verna_%28SX%2C_India%29_front_8.14.23.jpg/320px-2023_Hyundai_Verna_%28SX%2C_India%29_front_8.14.23.jpg",
                            IsActive = true,
                            IsAvailable = true,
                            Make = "Hyundai",
                            Model = "Verna",
                            PricePerDay = 280m,
                            PricePerKm = 11m,
                            RegistrationNumber = "MH14GH7890",
                            SeatingCapacity = 5,
                            VehicleCategoryId = 2,
                            VehicleType = "Sedan",
                            Year = 2023
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelType = "Petrol",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Tata_Nexon_EV_Max_%28facelift%2C_front%29%2C_Kolkata_2023.jpg/320px-Tata_Nexon_EV_Max_%28facelift%2C_front%29%2C_Kolkata_2023.jpg",
                            IsActive = true,
                            IsAvailable = true,
                            Make = "Tata",
                            Model = "Nexon",
                            PricePerDay = 320m,
                            PricePerKm = 13m,
                            RegistrationNumber = "TN07IJ8901",
                            SeatingCapacity = 5,
                            VehicleCategoryId = 2,
                            VehicleType = "SUV",
                            Year = 2023
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelType = "Diesel",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/2023_BMW_X1_xDrive23i_%28U11%29%2C_front_8.13.23.jpg/320px-2023_BMW_X1_xDrive23i_%28U11%29%2C_front_8.13.23.jpg",
                            IsActive = true,
                            IsAvailable = true,
                            Make = "BMW",
                            Model = "X1",
                            PricePerDay = 500m,
                            PricePerKm = 20m,
                            RegistrationNumber = "DL08EF9012",
                            SeatingCapacity = 5,
                            VehicleCategoryId = 3,
                            VehicleType = "SUV",
                            Year = 2023
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelType = "Petrol",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Mercedes-Benz_W206_IMG_6639.jpg/320px-Mercedes-Benz_W206_IMG_6639.jpg",
                            IsActive = true,
                            IsAvailable = true,
                            Make = "Mercedes-Benz",
                            Model = "C-Class",
                            PricePerDay = 600m,
                            PricePerKm = 22m,
                            RegistrationNumber = "MH01KL1234",
                            SeatingCapacity = 5,
                            VehicleCategoryId = 3,
                            VehicleType = "Sedan",
                            Year = 2023
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelType = "Diesel",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Audi_Q3_F3_IMG_4571.jpg/320px-Audi_Q3_F3_IMG_4571.jpg",
                            IsActive = true,
                            IsAvailable = true,
                            Make = "Audi",
                            Model = "Q3",
                            PricePerDay = 550m,
                            PricePerKm = 21m,
                            RegistrationNumber = "KA03MN2345",
                            SeatingCapacity = 5,
                            VehicleCategoryId = 3,
                            VehicleType = "SUV",
                            Year = 2022
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelType = "Diesel",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Mahindra_Scorpio-N_front.jpg/320px-Mahindra_Scorpio-N_front.jpg",
                            IsActive = true,
                            IsAvailable = true,
                            Make = "Mahindra",
                            Model = "Scorpio N",
                            PricePerDay = 400m,
                            PricePerKm = 15m,
                            RegistrationNumber = "TN09GH3456",
                            SeatingCapacity = 7,
                            VehicleCategoryId = 4,
                            VehicleType = "SUV",
                            Year = 2023
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelType = "Diesel",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/2022_Toyota_Innova_Crysta_%28AN140%2C_facelift%29_GX_MPV_%282022-09-17%29_01.jpg/320px-2022_Toyota_Innova_Crysta_%28AN140%2C_facelift%29_GX_MPV_%282022-09-17%29_01.jpg",
                            IsActive = true,
                            IsAvailable = true,
                            Make = "Toyota",
                            Model = "Innova Crysta",
                            PricePerDay = 420m,
                            PricePerKm = 16m,
                            RegistrationNumber = "GJ06PQ4567",
                            SeatingCapacity = 7,
                            VehicleCategoryId = 4,
                            VehicleType = "Van",
                            Year = 2022
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelType = "Diesel",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/2022_Kia_Carens_1.5_Diesel_Luxury_Plus_%28front%29.jpg/320px-2022_Kia_Carens_1.5_Diesel_Luxury_Plus_%28front%29.jpg",
                            IsActive = true,
                            IsAvailable = true,
                            Make = "Kia",
                            Model = "Carens",
                            PricePerDay = 380m,
                            PricePerKm = 14m,
                            RegistrationNumber = "RJ14RS5678",
                            SeatingCapacity = 6,
                            VehicleCategoryId = 4,
                            VehicleType = "Van",
                            Year = 2023
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelType = "Diesel",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Tata_Ace_Gold_%28front%29.jpg/320px-Tata_Ace_Gold_%28front%29.jpg",
                            IsActive = true,
                            IsAvailable = true,
                            Make = "Tata",
                            Model = "Ace",
                            PricePerDay = 600m,
                            PricePerKm = 25m,
                            RegistrationNumber = "GJ05IJ7890",
                            SeatingCapacity = 3,
                            VehicleCategoryId = 5,
                            VehicleType = "Truck",
                            Year = 2021
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelType = "Diesel",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Mahindra_Bolero_Pik-Up_Extra-Long_flatbed_%28front%29.jpg/320px-Mahindra_Bolero_Pik-Up_Extra-Long_flatbed_%28front%29.jpg",
                            IsActive = true,
                            IsAvailable = true,
                            Make = "Mahindra",
                            Model = "Bolero Pickup",
                            PricePerDay = 650m,
                            PricePerKm = 26m,
                            RegistrationNumber = "MH04TU6789",
                            SeatingCapacity = 3,
                            VehicleCategoryId = 5,
                            VehicleType = "Truck",
                            Year = 2022
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelType = "Diesel",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Ashok_Leyland_Dost%2B_CNG_%28front%29.jpg/320px-Ashok_Leyland_Dost%2B_CNG_%28front%29.jpg",
                            IsActive = true,
                            IsAvailable = true,
                            Make = "Ashok Leyland",
                            Model = "Dost",
                            PricePerDay = 700m,
                            PricePerKm = 28m,
                            RegistrationNumber = "KA02VW7890",
                            SeatingCapacity = 3,
                            VehicleCategoryId = 5,
                            VehicleType = "Truck",
                            Year = 2021
                        });
                });

            modelBuilder.Entity("backend.Models.VehicleCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PricePerKm")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("VehicleCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePrice = 150m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Budget-friendly vehicles",
                            DisplayOrder = 1,
                            IconUrl = "/icons/economy.svg",
                            IsActive = true,
                            Name = "Economy",
                            PricePerKm = 8m
                        },
                        new
                        {
                            Id = 2,
                            BasePrice = 300m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Comfortable premium vehicles",
                            DisplayOrder = 2,
                            IconUrl = "/icons/premium.svg",
                            IsActive = true,
                            Name = "Premium",
                            PricePerKm = 12m
                        },
                        new
                        {
                            Id = 3,
                            BasePrice = 500m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-end luxury vehicles",
                            DisplayOrder = 3,
                            IconUrl = "/icons/luxury.svg",
                            IsActive = true,
                            Name = "Luxury",
                            PricePerKm = 20m
                        },
                        new
                        {
                            Id = 4,
                            BasePrice = 400m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Spacious SUVs for group travel",
                            DisplayOrder = 4,
                            IconUrl = "/icons/suv.svg",
                            IsActive = true,
                            Name = "SUV",
                            PricePerKm = 15m
                        },
                        new
                        {
                            Id = 5,
                            BasePrice = 600m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Commercial vehicles for goods transport",
                            DisplayOrder = 5,
                            IconUrl = "/icons/commercial.svg",
                            IsActive = true,
                            Name = "Commercial",
                            PricePerKm = 25m
                        });
                });

            modelBuilder.Entity("backend.Models.Booking", b =>
                {
                    b.HasOne("backend.Models.Coupon", "Coupon")
                        .WithMany("Bookings")
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("backend.Models.Customer", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.Driver", "Driver")
                        .WithMany("Bookings")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("backend.Models.Vehicle", "Vehicle")
                        .WithMany("Bookings")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Coupon");

                    b.Navigation("Customer");

                    b.Navigation("Driver");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("backend.Models.CarpoolBooking", b =>
                {
                    b.HasOne("backend.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.Payment", "Payment")
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("backend.Models.RideOffer", "RideOffer")
                        .WithMany("CarpoolBookings")
                        .HasForeignKey("RideOfferId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Payment");

                    b.Navigation("RideOffer");
                });

            modelBuilder.Entity("backend.Models.Notification", b =>
                {
                    b.HasOne("backend.Models.Customer", "Customer")
                        .WithMany("Notifications")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("backend.Models.Payment", b =>
                {
                    b.HasOne("backend.Models.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Models.Customer", "Customer")
                        .WithMany("Payments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("backend.Models.Review", b =>
                {
                    b.HasOne("backend.Models.Booking", "Booking")
                        .WithMany("Reviews")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.Customer", "Customer")
                        .WithMany("Reviews")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.Driver", "Driver")
                        .WithMany("Reviews")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("backend.Models.Vehicle", "Vehicle")
                        .WithMany("Reviews")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Booking");

                    b.Navigation("Customer");

                    b.Navigation("Driver");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("backend.Models.RideOffer", b =>
                {
                    b.HasOne("backend.Models.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("backend.Models.RideRequest", b =>
                {
                    b.HasOne("backend.Models.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("backend.Models.Route", b =>
                {
                    b.HasOne("backend.Models.Booking", "Booking")
                        .WithOne("Route")
                        .HasForeignKey("backend.Models.Route", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("backend.Models.UserAccount", b =>
                {
                    b.HasOne("backend.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("backend.Models.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Customer");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("backend.Models.Vehicle", b =>
                {
                    b.HasOne("backend.Models.Driver", "CurrentDriver")
                        .WithMany("Vehicles")
                        .HasForeignKey("CurrentDriverId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("backend.Models.VehicleCategory", "VehicleCategory")
                        .WithMany("Vehicles")
                        .HasForeignKey("VehicleCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentDriver");

                    b.Navigation("VehicleCategory");
                });

            modelBuilder.Entity("backend.Models.Booking", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("Reviews");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("backend.Models.Coupon", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("backend.Models.Customer", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Notifications");

                    b.Navigation("Payments");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("backend.Models.Driver", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Reviews");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("backend.Models.RideOffer", b =>
                {
                    b.Navigation("CarpoolBookings");
                });

            modelBuilder.Entity("backend.Models.Vehicle", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("backend.Models.VehicleCategory", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
