import { useEffect, useState } from 'react';
import { Link, Routes, Route, useNavigate } from 'react-router-dom';
import { Activity, Car, ClipboardList, LogOut, Search, Users } from 'lucide-react';
import { bookingService, driverService, vehicleService } from '../services';
import { Badge, EmptyState, Loader } from '../components';

const listFrom = (response) => response?.data?.items || response?.data || response?.items || response || [];

function AdminHome({ data }) {
  const pending = data.bookings.filter(booking => ['Pending', 'Confirmed', 'DriverAssigned'].includes(booking.status));
  const cards = [['Open rides', pending.length, ClipboardList], ['Drivers', data.drivers.length, Users], ['Vehicles', data.vehicles.length, Car]];
  return <div className="space-y-8"><div><h1 className="text-2xl font-extrabold text-gray-900">Admin Dashboard</h1><p className="text-gray-500 mt-1">Monitor ride requests and operations.</p></div><div className="grid grid-cols-1 sm:grid-cols-3 gap-5">{cards.map(([label, value, Icon]) => <div key={label} className="bg-white rounded-2xl p-5 border border-gray-100 shadow-sm"><Icon className="w-5 h-5 text-primary-600 mb-3" /><p className="text-2xl font-extrabold">{value}</p><p className="text-sm text-gray-500">{label}</p></div>)}</div><section className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden"><div className="p-5 border-b border-gray-100 flex items-center justify-between"><h2 className="font-bold">Ride status</h2><Link to="status" className="text-sm text-primary-600 font-semibold">Open status check</Link></div>{pending.length === 0 ? <EmptyState icon={Activity} title="No active ride requests" description="New customer bookings will appear here." /> : <div className="divide-y divide-gray-100">{pending.slice(0, 8).map(booking => <div key={booking.id} className="p-5 flex items-center justify-between gap-4"><div><p className="font-semibold">Ride #{booking.id}</p><p className="text-sm text-gray-500">{booking.pickupLocation} to {booking.dropLocation}</p></div><Badge status={booking.status} /></div>)}</div>}</section></div>;
}

function StatusCheck({ data, refresh }) {
  const [driverSearch, setDriverSearch] = useState('');
  const [assigning, setAssigning] = useState(null);
  const drivers = data.drivers.filter(driver => {
    const term = driverSearch.trim().toLowerCase();
    return driver.isActive && (!term || `${driver.firstName} ${driver.lastName} ${driver.email} ${driver.phoneNumber}`.toLowerCase().includes(term));
  });
  const rejectedRequests = bookingId => data.rideRequests.filter(request => request.bookingId === bookingId && (request.status === 'Rejected' || request.status === 2));
  const assign = async (bookingId, driverId) => { if (!driverId) return; setAssigning(bookingId); try { await bookingService.assignDriver(bookingId, Number(driverId)); await refresh(); } finally { setAssigning(null); } };
  return <div className="space-y-6"><div><h1 className="text-2xl font-extrabold text-gray-900">Ride Status Check</h1><p className="text-gray-500 mt-1">Review routes, assign drivers, and monitor ride progress.</p></div><div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-4"><label className="relative block max-w-md"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" /><input value={driverSearch} onChange={event => setDriverSearch(event.target.value)} placeholder="Search driver name, email, or phone" className="w-full pl-9 pr-4 py-2.5 border border-gray-200 rounded-lg text-sm focus:ring-2 focus:ring-primary-500 outline-none" /></label><p className="text-xs text-gray-400 mt-2">{drivers.length} active driver{drivers.length === 1 ? '' : 's'} available for assignment</p></div><div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden">{data.bookings.length === 0 ? <EmptyState icon={ClipboardList} title="No bookings yet" description="Customer bookings will appear here after registration and checkout." /> : <div className="divide-y divide-gray-100">{data.bookings.map(booking => <div key={booking.id} className="p-5 space-y-3"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-bold">Ride #{booking.id}</p><p className="text-sm text-gray-600">{booking.pickupLocation} to {booking.dropLocation}</p><p className="text-xs text-gray-400 mt-1">Customer: {booking.customerName || 'Customer'} · Payment: {booking.paymentStatus || 'Pending'}</p>{rejectedRequests(booking.id).map(request => <p key={request.id} className="text-xs text-red-600 mt-1">{request.driverName || 'A driver'} rejected this ride. Choose another driver.</p>)}</div><Badge status={booking.status} /></div><select disabled={assigning === booking.id} value={booking.driverId || ''} onChange={event => assign(booking.id, event.target.value)} className="w-full sm:w-80 px-3 py-2 border border-gray-200 rounded-lg text-sm"><option value="">Assign a driver</option>{drivers.map(driver => <option key={driver.id} value={driver.id}>{driver.firstName} {driver.lastName} · {driver.status}{driver.isVerified ? '' : ' · Pending verification'}</option>)}</select>{booking.driverId && <p className="text-sm text-green-700 font-semibold">Assigned to {booking.driverName || `driver #${booking.driverId}`} {booking.driverPhone ? `· ${booking.driverPhone}` : ''}</p>}</div>)}</div>}</div></div>;
}

export default function AdminDashboard() {
  const navigate = useNavigate();
  const [data, setData] = useState(null);
  const load = () => Promise.all([bookingService.getAll({ pageSize: 100 }), driverService.getAll({ pageSize: 100 }), vehicleService.getAll({ pageSize: 100 }), bookingService.getAllRideRequests()]).then(([bookings, drivers, vehicles, rideRequests]) => setData({ bookings: listFrom(bookings), drivers: listFrom(drivers), vehicles: listFrom(vehicles), rideRequests: listFrom(rideRequests) }));
  useEffect(() => { load(); }, []);
  if (!data) return <Loader fullPage />;
   return <div className="flex min-h-screen pt-16 bg-gray-50"><aside className="w-64 bg-gray-900 text-white p-5 flex flex-col"><h2 className="font-bold text-lg mb-6">Admin Portal</h2><nav className="space-y-2 flex-1"><Link className="flex items-center gap-3 px-3 py-2 rounded-lg hover:bg-gray-800" to="/admin"><Activity className="w-4 h-4" />Dashboard</Link><Link className="flex items-center gap-3 px-3 py-2 rounded-lg hover:bg-gray-800" to="/admin/status"><ClipboardList className="w-4 h-4" />Status Check</Link></nav><button onClick={() => navigate('/login')} className="flex items-center gap-3 px-3 py-2 rounded-lg text-red-300 hover:bg-gray-800"><LogOut className="w-4 h-4" />Sign Out</button></aside><main className="flex-1 p-8"><Routes><Route index element={<AdminHome data={data} />} /><Route path="status" element={<StatusCheck data={data} refresh={load} />} /></Routes>{data.rideRequests.some(request => request.status === 'Rejected' || request.status === 2) && <p className="mt-3 text-sm font-semibold text-red-600">A driver rejected a paid ride request. Open Status Check to choose another driver.</p>}</main></div>;
  }
